###################################################################################################
# 📄 INICIALIZAÇÕES
###################################################################################################

# docker-compose up --build
# docker-compose up -d
# docker-compose down

###################################################################################################
# 🔶 SERVIÇOS
###################################################################################################

version: '3.8'

services:
  # 🔶 /GO-API BACKEND SERVICE
  go-api:
    build: ./go-api
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - ocr-service

  # 🔶 /OCR SERVICE (PYTHON)
  ocr-service:
    build: ./ocr-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  # 🔶 /MONGO DATABASE SERVICE
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db/schema/init.js:/docker-entrypoint-initdb.d/init.js
